---
- name: password | Install user template
  ansible.builtin.template:
    src: 01_users.j2
    dest: /etc/grub.d/01_users
    owner: root
    group: root
    mode: '0700'
  notify:
    - Update grub

- name: password | Add --unrestricted
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: '^CLASS="(((?!--unrestricted).)*)"$'
    replace: 'CLASS="\1 --unrestricted"'
  with_items: "{{ grub_password_unrestricted_files }}"
  when:
    - grub_password_unrestricted
  notify:
    - Update grub
